// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjzSl-M5bOU0t4RzvLM1LkWSfVBtSTp4o',
    appId: '1:132839856528:android:fd5c3bc8038ac67fdebb15',
    messagingSenderId: '132839856528',
    projectId: 'ilayki-9c3e1',
    databaseURL: 'https://ilayki-9c3e1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ilayki-9c3e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQyf6dCQNf9_ui_l_1ywS8F-VbVyRGvlc',
    appId: '1:132839856528:ios:d05934668506b030debb15',
    messagingSenderId: '132839856528',
    projectId: 'ilayki-9c3e1',
    databaseURL: 'https://ilayki-9c3e1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ilayki-9c3e1.appspot.com',
    androidClientId: '132839856528-758h9hdmob2aj2t6onmf6t4423mel8n5.apps.googleusercontent.com',
    iosClientId: '132839856528-19qdalekrvn03msj6kbvvdt39r5vorj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ilayki',
  );
}
